# Generated by Django 3.0.8 on 2021-02-15 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0005_auto_20210216_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='high_school',
            field=models.CharField(blank=True, default='Name of High school', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='read',
            field=models.CharField(blank=True, default='Course of study', max_length=100, null=True),
        ),
    ]
